version: "3"

services:


  # worker:
  #   image: lisa-worker
  #   build:
  #     context: .
  #     dockerfile: ../worker/Dockerfile
  #   volumes:
  #     - "../../data/storage:/home/lisa/data/storage"
  #   devices:
  #     - "/dev/net/tun:/dev/net/tun"
  #   sysctls:
  #     - "net.ipv4.ping_group_range=0 2000000"
  #     - "net.ipv6.conf.all.disable_ipv6=0"
  #     - "net.ipv4.ip_forward=1"
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     lisanet:
  #       ipv4_address: 172.44.0.2
  #   restart: on-failure

  # worker:
  #   image: ubuntu:18.04
  #   command: "bash"
  #   sysctls:
  #     - "net.ipv4.ping_group_range=0 2000000"
  #     - "net.ipv6.conf.all.disable_ipv6=0"
  #     - "net.ipv4.ip_forward=1"
  #   networks:
  #     lisanet: 
  #       ipv4_address: 172.44.0.10
  #   restart: always


  mitmproxy:
    image: lisa-mitmproxy
    ports:
      - 8080:8080
    networks:
      lisanet:
        ipv4_address: 172.44.0.15
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure

networks:
  lisanet:
    ipam:
      driver: default
      config:
        - subnet: 172.44.0.0/24
